### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by cmol** [littleiffel/dokuwiki-slack-integration#5]
Hi,

I have a fork of your project for RocketChat+, which is basically a clone of Slack.

I've had a slack user reporting that my plugin works for him with slack (which is a bit of a surprise to me), but that your plugin does not:
https://github.com/Fab-IT-ApS/dokuwiki-rocketchat-integration/issues/3

Are you still developing this plugin? In that case, there's a bug that I'm not sure of what is. If not, you're welcome to reference my fork as possibly working.

Sorry for the weird issue, didn't know how else to convey this info.

**Comment by littleiffel** [comment]
HI @cmol ,

well thanks for the issue. No thi soriject is not much alive, I created a quick fix to get it working. So far I wasn't even aware that people would still use it? I  think I never had a bug report :)

Sure I will add your fork as reference so people can use it:

**Comment by littleiffel** [comment]
Closed :)

**Comment by cmol** [comment]
Yeah, I'm also wondering why you didn't just get a bug report but what whatever works. If you feel like working on a joint plugin in the future I'll be down for that, though I'm not sure if Slack and RocketChat will keep their compatibility :)
